- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
  vars_files:
  - files.yaml
  tasks:
  - name: create ec2  
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instance_output

  - name: print ec2_instance_output
    ansible.builtin.debug:
      msg: "{{ ec2_instance_output }}"
  
  - name: Create Route53 records for all instances (frontend gets both public & private)
    amazon.aws.route53:
      state: present
      zone: "{{ zone_name }}"
      record: "{{ item.record }}"
      type: A
      ttl: 1
      value: "{{ item.value }}"
      overwrite: true
      wait: true
    loop: "{{ route53_records }}"
    vars:
      route53_records: >
        {%- set records = [] -%}
        {%- for r in ec2_instance_output.results -%}
          {%- set name = r.item -%}
          {%- set private_ip = r.instances[0].private_ip_address -%}
          {%- set public_ip = r.instances[0].public_ip_address -%}

          # Private record for every instance
          {%- set _ = records.append({'record': name ~ '.' ~ zone_name, 'value': private_ip}) -%}

          # Public record only for frontend
          {%- if name == 'frontend' -%}
            {%- set _ = records.append({'record': zone_name, 'value': public_ip}) -%}
          {%- endif -%}
        {%- endfor -%}
        {{ records }}
