- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
  vars_files:
  - files.yaml
  tasks:
  - name: create ec2  
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instance_output

  - name: print ec2_instance_output
    ansible.builtin.debug:
      msg: "{{ ec2_instance_output }}"
  
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone_name }}"
      record: "{{ item.item }}.{{ zone_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instance_output.results }}"
    when: item.item == "frontend"