- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
  vars_files:
  - files.yaml
  tasks:
  - name: create ec2  
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instance_output

  - name: print ec2_instance_output
    ansible.builtin.debug:
      msg: "{{ ec2_instance_output }}"
  
  - name: Create Route53 records for all instances
    amazon.aws.route53:
      state: present
      zone: "{{ zone_name }}"
      record: "{{ item.record }}"
      type: A
      ttl: 1
      value: "{{ item.value }}"
      overwrite: true
      wait: true
    loop: >
      {{
        ec2_instance_output.results
        | map('extract', 'instances')
        | map('first')
        | list
        | map('community.general.dict', {
            'record': item.tags.Name + '.' + zone_name,
            'value': item.private_ip_address
          })
        | list
        + [
            {'record': 'daws2025.online',
            'value': (ec2_instance_output.results | selectattr('item', 'equalto', 'frontend') | first).instances[0].public_ip_address}
          ]
      }}
