- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
  vars_files:
  - files.yaml
  tasks:
  - name: create ec2  
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instance_output

  - name: print ec2_instance_output
    ansible.builtin.debug:
      msg: "{{ ec2_instance_output }}"
  
  - name: Create Route53 records for all instances
    amazon.aws.route53:
      state: present
      zone: "{{ zone_name }}"
      record: "{{ item.record }}"
      type: A
      ttl: 1
      value: "{{ item.value }}"
      overwrite: true
      wait: true
    loop: "{{ query('list', records) }}"
    vars:
      records: >
        {% set r = [] %}
        {% for i in ec2_instance_output.results %}
          {% set name = i.item %}
          {% set private_ip = i.instances[0].private_ip_address %}
          {% set public_ip = i.instances[0].public_ip_address %}
          {% set _ = r.append({'record': name + '.' + zone_name, 'value': private_ip}) %}
          {% if name == 'frontend' %}
            {% set _ = r.append({'record': zone_name, 'value': public_ip}) %}
          {% endif %}
        {% endfor %}
        {{ r }}
