- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
  vars_files:
  - files.yaml
  tasks:
  - name: create ec2  
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ image_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instance_output

  - name: print ec2_instance_output
    ansible.builtin.debug:
      msg: "{{ ec2_instance_output }}"